// Curated GenLayer / tech-ecosystem word bank used to auto-fill the seed
// crossword puzzles (Phase 4). Each entry is a unique uppercase word with a
// themed clue. Kept intentionally broad across lengths so the backtracking
// filler (scripts/crossword-fill.ts) has enough candidates per slot length.

export type WordEntry = { word: string; clue: string };

const RAW: WordEntry[] = [
  { word: 'AI', clue: 'Artificial ___' },
  { word: 'ML', clue: 'Machine learning, for short' },
  { word: 'IO', clue: 'Input/output, briefly' },
  { word: 'ID', clue: 'Identifier, briefly' },
  { word: 'UI', clue: 'What a user sees, briefly' },
  { word: 'OS', clue: 'Windows or macOS, briefly' },
  { word: 'VM', clue: 'Virtual ___' },
  { word: 'DB', clue: 'Postgres, e.g., briefly' },
  { word: 'GO', clue: 'Language named after a board game' },
  { word: 'PY', clue: 'Python file extension' },
  { word: 'JS', clue: 'Scripting language of the web, briefly' },
  { word: 'GAS', clue: 'Fee to execute a transaction' },
  { word: 'KEY', clue: 'Private ___' },
  { word: 'LOG', clue: 'Append-only record' },
  { word: 'RUN', clue: 'Execute a script' },
  { word: 'DEV', clue: 'Builder, informally' },
  { word: 'BUG', clue: 'Code defect' },
  { word: 'APP', clue: 'Mobile software' },
  { word: 'WEB', clue: 'The ___3 movement' },
  { word: 'NET', clue: 'Mainnet or testnet' },
  { word: 'BOT', clue: 'Automated agent' },
  { word: 'SDK', clue: 'Developer toolkit, briefly' },
  { word: 'CLI', clue: 'Terminal tool, briefly' },
  { word: 'API', clue: 'Interface for programs, briefly' },
  { word: 'GIT', clue: 'Version control system' },
  { word: 'ENV', clue: 'Config file prefix' },
  { word: 'ARG', clue: 'Function input' },
  { word: 'DOM', clue: 'Document Object Model, briefly' },
  { word: 'ZIP', clue: 'Compress a file' },
  { word: 'RAM', clue: 'Fast memory' },
  { word: 'CPU', clue: 'Processor, briefly' },
  { word: 'GPU', clue: 'Graphics chip, briefly' },
  { word: 'SQL', clue: 'Query language, briefly' },
  { word: 'JSON', clue: 'Common data format' },
  { word: 'NODE', clue: 'Network participant' },
  { word: 'HASH', clue: 'Fixed-size digest' },
  { word: 'FORK', clue: 'Chain split' },
  { word: 'PEER', clue: 'Fellow node' },
  { word: 'MESH', clue: 'Peer-to-peer topology' },
  { word: 'VOTE', clue: "Validator's ballot" },
  { word: 'CODE', clue: 'Source text' },
  { word: 'TEST', clue: 'CI step before deploy' },
  { word: 'LOOP', clue: 'Repeating control structure' },
  { word: 'BYTE', clue: '8 bits' },
  { word: 'STAKE', clue: 'Bonded GEN' },
  { word: 'CHAIN', clue: 'Blocks linked together' },
  { word: 'BLOCK', clue: 'Unit of a ledger' },
  { word: 'TOKEN', clue: 'Fungible unit of value' },
  { word: 'ORACLE', clue: 'Off-chain data feeder' },
  { word: 'LEDGER', clue: 'Record of all transactions' },
  { word: 'QUORUM', clue: 'Minimum votes needed' },
  { word: 'ROLLUP', clue: 'Layer-2 scaling technique' },
  { word: 'LAYER', clue: 'Protocol tier' },
  { word: 'PROOF', clue: 'Evidence of validity' },
  { word: 'SYBIL', clue: '___ attack, fake identities' },
  { word: 'GOSSIP', clue: 'Peer message propagation' },
  { word: 'RELAY', clue: 'Message forwarder' },
  { word: 'CLIENT', clue: 'App connecting to a node' },
  { word: 'SERVER', clue: 'Backend host' },
  { word: 'AGENT', clue: 'Autonomous actor' },
  { word: 'MODEL', clue: 'LLM, essentially' },
  { word: 'TRAIN', clue: 'Teach a model' },
  { word: 'QUERY', clue: 'Database request' },
  { word: 'INDEX', clue: 'Lookup structure' },
  { word: 'CACHE', clue: 'Redis, for one' },
  { word: 'ASYNC', clue: 'Non-blocking, briefly' },
  { word: 'EVENT', clue: 'Emitted log entry' },
  { word: 'QUEUE', clue: 'FIFO structure' },
  { word: 'STREAM', clue: 'Continuous data flow' },
  { word: 'ARRAY', clue: 'Ordered list structure' },
  { word: 'STACK', clue: 'LIFO structure' },
  { word: 'GRAPH', clue: 'Nodes and edges' },
  { word: 'ROUTE', clue: 'API endpoint path' },
  { word: 'GRID', clue: 'This app\'s namesake shape' },
  { word: 'ROOM', clue: 'Where a game session happens' },
  { word: 'TIMER', clue: 'Countdown widget' },
  { word: 'ADMIN', clue: 'Dashboard operator' },
  { word: 'ROLE', clue: 'Permission level' },
  { word: 'AUTH', clue: 'Login check, briefly' },
  { word: 'DEPLOY', clue: 'Ship to production' },
  { word: 'MERGE', clue: 'Combine git branches' },
  { word: 'BRANCH', clue: 'Git divergence point' },
  { word: 'COMMIT', clue: 'Git snapshot' },
  { word: 'REPO', clue: 'Git project, briefly' },
  { word: 'DEBUG', clue: 'Hunt for the bug' },
  { word: 'PROMPT', clue: 'LLM input text' },
  { word: 'INFER', clue: 'Run a model forward pass' },
  { word: 'FINALITY', clue: 'Irreversibility of a block' },
  { word: 'EPOCH', clue: 'Consensus time period' },
  { word: 'SLOT', clue: 'Scheduled block interval' },
  { word: 'MERKLE', clue: '___ tree, hash structure' },
  { word: 'VALIDATOR', clue: 'Node that confirms transactions' },
  { word: 'CONSENSUS', clue: 'Agreement among validators' },
  { word: 'CONTRACT', clue: 'Self-executing code, intelligent ___' },
  { word: 'BUILDER', clue: 'Developer shipping on the protocol' },
  { word: 'PROTOCOL', clue: 'Set of network rules' },
  { word: 'ECOSYSTEM', clue: 'Community of builders and users' },
  { word: 'WALLET', clue: 'Where keys are stored' },
  { word: 'GENLAYER', clue: 'This ecosystem\'s name' },
  { word: 'EQUIVALENCE', clue: 'Principle used to reconcile validator outputs' },
  { word: 'TRUST', clue: 'What consensus builds' },
  { word: 'VERIFY', clue: 'Check a proof' },
  { word: 'SIGN', clue: 'Authorize with a key' },
  { word: 'CROSSWORD', clue: 'What you are solving right now' },
  { word: 'PUZZLE', clue: 'Brain teaser' },
  { word: 'PLAYER', clue: 'Someone competing in a room' },
  { word: 'SCORE', clue: 'Points earned' },
  { word: 'LEADERBOARD', clue: 'Ranking display' },
  { word: 'SUBMIT', clue: 'Send in your answers' },
  { word: 'ANSWER', clue: 'Solution to a clue' },
  { word: 'CLUE', clue: 'Hint toward an answer' },
  { word: 'ACROSS', clue: 'Horizontal direction in a crossword' },
  { word: 'DOWN', clue: 'Vertical direction in a crossword' },
  { word: 'TEMPLATE', clue: 'Reusable grid shape' },
  { word: 'DESIGNER', clue: 'One who builds a custom grid' },
  { word: 'INTELLIGENT', clue: '___ contract, GenLayer\'s term for a smart contract' },
  { word: 'DECENTRALIZED', clue: 'Not controlled by one party' },
  { word: 'PROTOCOL', clue: 'Rules governing the network' },
  { word: 'NETWORK', clue: 'Set of connected nodes' },
  { word: 'BACKEND', clue: 'Server-side layer' },
  { word: 'DATASET', clue: 'Training data collection' },
  { word: 'CLUSTER', clue: 'Group of servers' },
  { word: 'UPGRADE', clue: 'Protocol version bump' },
  { word: 'MAINNET', clue: 'Live production chain' },
  { word: 'TESTNET', clue: 'Practice chain before mainnet' },
  { word: 'KEYPAIR', clue: 'Public and private key together' },
  { word: 'GATEWAY', clue: 'Entry point to a network' },
  { word: 'RUNTIME', clue: 'Execution environment' },
  { word: 'WEBHOOK', clue: 'HTTP callback trigger' },
  { word: 'SANDBOX', clue: 'Isolated test environment' },
  { word: 'LATENCY', clue: 'Delay before a response' },
  { word: 'COMPILE', clue: 'Turn source into bytecode' },
  { word: 'PIPELINE', clue: 'CI/CD build chain' },
  { word: 'ENDPOINT', clue: 'API URL target' },
  { word: 'FRONTEND', clue: 'Client-side layer' },
  { word: 'SNAPSHOT', clue: 'Point-in-time state copy' },
  { word: 'DEADLINE', clue: 'Room submission cutoff' },
  { word: 'COMPILER', clue: 'Source-to-bytecode translator' },
  { word: 'CALLBACK', clue: 'Function passed to run later' },
  { word: 'OPERATOR', clue: 'Node runner' },
  { word: 'EXECUTOR', clue: 'One that runs a transaction' },
  { word: 'DATABASE', clue: 'Supabase, essentially' },
  { word: 'FIREWALL', clue: 'Network security barrier' },
  { word: 'FUNCTION', clue: 'Reusable block of code' },
  { word: 'VARIABLE', clue: 'Named storage in code' },
  { word: 'BANDWIDTH', clue: 'Data throughput capacity' },
  { word: 'INTERFACE', clue: 'Contract between systems' },
  { word: 'THROUGHPUT', clue: 'Transactions processed per second' },
  { word: 'MIDDLEWARE', clue: 'Layer between client and server' },
  { word: 'ATTESTOR', clue: 'One who attests to a result' },
  { word: 'REGISTRY', clue: 'Where packages are published' },
  { word: 'SEQUENCE', clue: 'Ordered series of blocks' },
  { word: 'BOOTSTRAP', clue: 'Initial node setup' },
  { word: 'RESOLVER', clue: 'Name lookup service' },
  { word: 'DISPATCH', clue: 'Route a request onward' },
  { word: 'CHECKSUM', clue: 'Error-detecting value' },
  { word: 'ARBITER', clue: 'Neutral decision maker' },
  { word: 'REWARD', clue: 'Incentive for validating' },
  { word: 'PENALTY', clue: 'Slashing consequence' },

  // Common short fill words — real crosswords lean on ordinary vocabulary
  // to make the grid fillable, not just theme terms.
  { word: 'AS', clue: 'In the role of' },
  { word: 'AT', clue: 'Located in' },
  { word: 'BE', clue: 'Exist' },
  { word: 'BY', clue: 'Next to' },
  { word: 'DO', clue: 'Perform an action' },
  { word: 'IF', clue: 'Conditional word' },
  { word: 'IN', clue: 'Inside of' },
  { word: 'IT', clue: 'Neuter pronoun' },
  { word: 'NO', clue: 'Negative reply' },
  { word: 'OF', clue: 'Belonging to' },
  { word: 'ON', clue: 'Switched active' },
  { word: 'OR', clue: 'Alternative conjunction' },
  { word: 'SO', clue: 'Therefore' },
  { word: 'TO', clue: 'Toward' },
  { word: 'UP', clue: 'Opposite of down' },
  { word: 'US', clue: 'Objective pronoun, plural' },
  { word: 'WE', clue: 'You and I' },
  { word: 'AGE', clue: 'Years lived' },
  { word: 'AIM', clue: 'Point a goal' },
  { word: 'ARM', clue: 'Limb with a hand' },
  { word: 'ART', clue: 'Creative work' },
  { word: 'ASK', clue: 'Pose a question' },
  { word: 'BAD', clue: 'Not good' },
  { word: 'BIG', clue: 'Large in size' },
  { word: 'BOX', clue: 'Container shape' },
  { word: 'CAR', clue: 'Automobile' },
  { word: 'CUP', clue: 'Drinking vessel' },
  { word: 'DAY', clue: '24 hours' },
  { word: 'EAR', clue: 'Hearing organ' },
  { word: 'EAT', clue: 'Consume food' },
  { word: 'END', clue: 'Final point' },
  { word: 'ERA', clue: 'Time period' },
  { word: 'EYE', clue: 'Seeing organ' },
  { word: 'FAR', clue: 'Not near' },
  { word: 'FEW', clue: 'Not many' },
  { word: 'FIT', clue: 'In good shape' },
  { word: 'FLY', clue: 'Move through air' },
  { word: 'FOR', clue: 'On behalf of' },
  { word: 'FUN', clue: 'Enjoyable time' },
  { word: 'GOT', clue: 'Received, past tense' },
  { word: 'GUY', clue: 'Informal man' },
  { word: 'HAT', clue: 'Head covering' },
  { word: 'HIT', clue: 'Strike' },
  { word: 'HOT', clue: 'High temperature' },
  { word: 'ICE', clue: 'Frozen water' },
  { word: 'JOB', clue: 'Employment' },
  { word: 'JOY', clue: 'Great happiness' },
  { word: 'KEY', clue: 'Unlocks a door' },
  { word: 'LAW', clue: 'Legal rule' },
  { word: 'LEG', clue: 'Walking limb' },
  { word: 'LOT', clue: 'A great deal' },
  { word: 'LOW', clue: 'Not high' },
  { word: 'MAP', clue: 'Geographic chart' },
  { word: 'MIX', clue: 'Combine together' },
  { word: 'NEW', clue: 'Not old' },
  { word: 'NOW', clue: 'At this moment' },
  { word: 'ODD', clue: 'Strange' },
  { word: 'OLD', clue: 'Not young' },
  { word: 'ONE', clue: 'First number' },
  { word: 'OWN', clue: 'Possess' },
  { word: 'PAY', clue: 'Compensate' },
  { word: 'PEN', clue: 'Writing tool' },
  { word: 'PIE', clue: 'Dessert in a crust' },
  { word: 'RUN', clue: 'Move quickly on foot' },
  { word: 'SAD', clue: 'Not happy' },
  { word: 'SAT', clue: 'Sit, past tense' },
  { word: 'SEA', clue: 'Body of salt water' },
  { word: 'SET', clue: 'Put in place' },
  { word: 'SIX', clue: 'Number after five' },
  { word: 'SKY', clue: 'Above the clouds' },
  { word: 'SUN', clue: 'Star at the center' },
  { word: 'TAX', clue: 'Government levy' },
  { word: 'TEN', clue: 'Number after nine' },
  { word: 'TOP', clue: 'Highest point' },
  { word: 'TRY', clue: 'Attempt' },
  { word: 'TWO', clue: 'Number after one' },
  { word: 'USE', clue: 'Put to work' },
  { word: 'VAN', clue: 'Delivery vehicle' },
  { word: 'WAR', clue: 'Armed conflict' },
  { word: 'WAY', clue: 'Path or method' },
  { word: 'WIN', clue: 'Achieve victory' },
  { word: 'YES', clue: 'Affirmative reply' },
  { word: 'ZOO', clue: 'Animal park' },
  { word: 'ABLE', clue: 'Capable' },
  { word: 'AREA', clue: 'Region' },
  { word: 'BEST', clue: 'Top choice' },
  { word: 'BLUE', clue: 'Sky\'s color' },
  { word: 'BOAT', clue: 'Water vessel' },
  { word: 'BOLD', clue: 'Confident and daring' },
  { word: 'BOOK', clue: 'Bound pages' },
  { word: 'BOTH', clue: 'The two of them' },
  { word: 'CALL', clue: 'Phone someone' },
  { word: 'CARE', clue: 'Show concern' },
  { word: 'CASE', clue: 'Instance' },
  { word: 'CITY', clue: 'Large town' },
  { word: 'COOL', clue: 'Somewhat cold' },
  { word: 'COST', clue: 'Price' },
  { word: 'DARK', clue: 'Lacking light' },
  { word: 'DATA', clue: 'Facts and figures' },
  { word: 'DEEP', clue: 'Far down' },
  { word: 'DOOR', clue: 'Entry point' },
  { word: 'DOWN', clue: 'Opposite of up' },
  { word: 'EACH', clue: 'Every one' },
  { word: 'EASY', clue: 'Not hard' },
  { word: 'EDGE', clue: 'Border' },
  { word: 'FAST', clue: 'Quick' },
  { word: 'FILE', clue: 'Digital document' },
  { word: 'FINE', clue: 'Acceptable' },
  { word: 'FIRE', clue: 'Flame' },
  { word: 'FISH', clue: 'Aquatic animal' },
  { word: 'FIVE', clue: 'Number after four' },
  { word: 'FLAT', clue: 'Level' },
  { word: 'FREE', clue: 'No cost' },
  { word: 'FULL', clue: 'At capacity' },
  { word: 'GAME', clue: 'Match or contest' },
  { word: 'GIVE', clue: 'Hand over' },
  { word: 'GOOD', clue: 'Not bad' },
  { word: 'HALF', clue: 'One of two equal parts' },
  { word: 'HARD', clue: 'Difficult' },
  { word: 'HELP', clue: 'Assist' },
  { word: 'HERE', clue: 'In this place' },
  { word: 'HIGH', clue: 'Tall or elevated' },
  { word: 'HOLD', clue: 'Grip' },
  { word: 'HOME', clue: 'Where you live' },
  { word: 'HOUR', clue: '60 minutes' },
  { word: 'IDEA', clue: 'A thought' },
  { word: 'INTO', clue: 'Toward the inside of' },
  { word: 'ITEM', clue: 'Single object' },
  { word: 'JUMP', clue: 'Leap' },
  { word: 'JUST', clue: 'Merely' },
  { word: 'KEEP', clue: 'Retain' },
  { word: 'KIND', clue: 'Type, or gentle' },
  { word: 'KNOW', clue: 'Be certain of' },
  { word: 'LAST', clue: 'Final' },
  { word: 'LATE', clue: 'Not on time' },
  { word: 'LESS', clue: 'Not as much' },
  { word: 'LIFE', clue: 'Being alive' },
  { word: 'LIKE', clue: 'Enjoy' },
  { word: 'LINE', clue: 'Row or queue' },
  { word: 'LIST', clue: 'Enumerated items' },
  { word: 'LIVE', clue: 'Be alive' },
  { word: 'LONG', clue: 'Extended in length' },
  { word: 'LOOK', clue: 'Glance' },
  { word: 'LOVE', clue: 'Deep affection' },
  { word: 'MAKE', clue: 'Create' },
  { word: 'MANY', clue: 'A large number' },
  { word: 'MIND', clue: 'The brain, figuratively' },
  { word: 'MOST', clue: 'The greatest amount' },
  { word: 'MOVE', clue: 'Change position' },
  { word: 'MUCH', clue: 'A great amount' },
  { word: 'NAME', clue: 'What you\'re called' },
  { word: 'NEAR', clue: 'Close by' },
  { word: 'NEED', clue: 'Require' },
  { word: 'NEXT', clue: 'Following' },
  { word: 'NICE', clue: 'Pleasant' },
  { word: 'NINE', clue: 'Number after eight' },
  { word: 'NONE', clue: 'Not any' },
  { word: 'ONLY', clue: 'Solely' },
  { word: 'OPEN', clue: 'Not closed' },
  { word: 'OVER', clue: 'Above, or finished' },
  { word: 'PAGE', clue: 'Sheet in a book' },
  { word: 'PART', clue: 'Portion' },
  { word: 'PASS', clue: 'Go by' },
  { word: 'PAST', clue: 'Bygone times' },
  { word: 'PICK', clue: 'Choose' },
  { word: 'PLAN', clue: 'Scheme ahead' },
  { word: 'PLAY', clue: 'Have fun' },
  { word: 'PLUS', clue: 'In addition' },
  { word: 'POOL', clue: 'Swimming spot' },
  { word: 'PULL', clue: 'Draw toward you' },
  { word: 'PUSH', clue: 'Shove' },
  { word: 'RACE', clue: 'Speed contest' },
  { word: 'RATE', clue: 'Speed or price level' },
  { word: 'READ', clue: 'Peruse text' },
  { word: 'REAL', clue: 'Genuine' },
  { word: 'REST', clue: 'Relax' },
  { word: 'RISK', clue: 'Chance of loss' },
  { word: 'ROOM', clue: 'Space in a building' },
  { word: 'ROOT', clue: 'Base of a tree' },
  { word: 'RULE', clue: 'Regulation' },
  { word: 'SAFE', clue: 'Secure' },
  { word: 'SAME', clue: 'Identical' },
  { word: 'SAVE', clue: 'Keep for later' },
  { word: 'SEEK', clue: 'Search for' },
  { word: 'SEND', clue: 'Transmit' },
  { word: 'SHOW', clue: 'Display' },
  { word: 'SIDE', clue: 'One face of something' },
  { word: 'SIGN', clue: 'Symbol or gesture' },
  { word: 'SITE', clue: 'Location' },
  { word: 'SIZE', clue: 'Dimensions' },
  { word: 'SOFT', clue: 'Not hard' },
  { word: 'SOME', clue: 'An unspecified amount' },
  { word: 'SORT', clue: 'Arrange in order' },
  { word: 'SPOT', clue: 'A particular place' },
  { word: 'STAY', clue: 'Remain' },
  { word: 'STEP', clue: 'A single move' },
  { word: 'STOP', clue: 'Halt' },
  { word: 'SUCH', clue: 'Of that kind' },
  { word: 'SURE', clue: 'Certain' },
  { word: 'TAKE', clue: 'Grab' },
  { word: 'TALK', clue: 'Speak' },
  { word: 'TASK', clue: 'A job to do' },
  { word: 'TEAM', clue: 'Group working together' },
  { word: 'TELL', clue: 'Inform' },
  { word: 'TERM', clue: 'A defined word or period' },
  { word: 'THAN', clue: 'Comparison word' },
  { word: 'THAT', clue: 'Demonstrative pronoun' },
  { word: 'THEM', clue: 'Objective plural pronoun' },
  { word: 'THEN', clue: 'At that time' },
  { word: 'THIS', clue: 'Demonstrative pronoun, singular' },
  { word: 'TIME', clue: 'What a clock measures' },
  { word: 'TREE', clue: 'Tall plant with a trunk' },
  { word: 'TRUE', clue: 'Not false' },
  { word: 'TURN', clue: 'Rotate' },
  { word: 'TYPE', clue: 'Category' },
  { word: 'UPON', clue: 'On top of' },
  { word: 'USER', clue: 'One who operates an app' },
  { word: 'VARY', clue: 'Differ' },
  { word: 'VERY', clue: 'To a great extent' },
  { word: 'VIEW', clue: 'A sight' },
  { word: 'WAIT', clue: 'Stay until' },
  { word: 'WALK', clue: 'Move on foot' },
  { word: 'WANT', clue: 'Desire' },
  { word: 'WARM', clue: 'Mildly hot' },
  { word: 'WEAK', clue: 'Not strong' },
  { word: 'WEAR', clue: 'Have on the body' },
  { word: 'WEEK', clue: '7 days' },
  { word: 'WELL', clue: 'In good health' },
  { word: 'WENT', clue: 'Go, past tense' },
  { word: 'WHAT', clue: 'Interrogative pronoun' },
  { word: 'WHEN', clue: 'At what time' },
  { word: 'WHOM', clue: 'Objective form of who' },
  { word: 'WIDE', clue: 'Broad' },
  { word: 'WILD', clue: 'Untamed' },
  { word: 'WILL', clue: 'Future-tense helper verb' },
  { word: 'WISH', clue: 'Hope for' },
  { word: 'WITH', clue: 'Accompanied by' },
  { word: 'WORD', clue: 'A unit of language' },
  { word: 'WORE', clue: 'Wear, past tense' },
  { word: 'WORK', clue: 'Labor' },
  { word: 'YEAR', clue: '365 days' },
  { word: 'ZERO', clue: 'The number 0' },
  { word: 'ZONE', clue: 'Designated area' },
];

// De-duplicate by word just in case of accidental repeats above.
const seen = new Set<string>();
export const WORD_BANK: WordEntry[] = RAW.filter((entry) => {
  const key = entry.word.toUpperCase();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

export const WORDS_BY_LENGTH: Map<number, WordEntry[]> = new Map();
for (const entry of WORD_BANK) {
  const len = entry.word.length;
  if (!WORDS_BY_LENGTH.has(len)) WORDS_BY_LENGTH.set(len, []);
  WORDS_BY_LENGTH.get(len)!.push(entry);
}
